# Generated by Django 3.1.5 on 2022-05-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_ksh_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fxdq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dangerlevel', models.TextField(blank=True, db_column='dangerLevel', null=True)),
                ('provinceid', models.TextField(blank=True, db_column='provinceId', null=True)),
                ('provincename', models.TextField(blank=True, db_column='provinceName', null=True)),
                ('cityname', models.TextField(blank=True, db_column='cityName', null=True)),
                ('areaname', models.TextField(blank=True, db_column='areaName', null=True)),
            ],
            options={
                'db_table': 'fxdq',
                'managed': True,
            },
        ),
    ]
